language: python
matrix:
  include:
    - env: TOXENV=py27
      python: "2.7"
    - env: TOXENV=pypy
      python: "pypy"
    - env: TOXENV=py35
      python: "3.5"
    - env: TOXENV=py36
      python: "3.6"

install: pip install tox coverage

script:
  - coverage erase
  - tox
after_success:
  - pip install coveralls
  - coveralls
